### ISSUE TITLE
Problems with nested fragments

### ISSUE THREAD

**Issue by RinkeHoekstra** [hypergraphql/hypergraphql#18]
I'm trying to use nested fragments in a query to map onto a SKOS-XL schema, but get a 500 error because a `FragmentDefinition` cannot be cast onto an `OperationDefinition`. The query works fine without the fragments.

The query is:
```
fragment ConceptAttrs on Concept {
  preflabel {
    literalform
  }
  altlabel{
    literalform
  }
}

fragment ConceptRecursive on Concept {
	...ConceptAttrs
  broader {
    ...ConceptAttrs
    broader{
      ...ConceptAttrs
      broader {
        ...ConceptAttrs
        broader {
          ...ConceptAttrs
        }
      }
    }
  }
  narrower {
    ...ConceptAttrs
  }
}

{
  Concept_GET(limit: 1) { 
    _id
    ...ConceptRecursive
  }
}
```

The error trace is:

```
2018-11-05 09:11:17 ERROR GeneralError:54 -
java.lang.ClassCastException: graphql.language.FragmentDefinition cannot be cast to graphql.language.OperationDefinition
	at org.hypergraphql.datafetching.ExecutionForestFactory.getExecutionForest(ExecutionForestFactory.java:15)
	at org.hypergraphql.services.HGQLQueryService.results(HGQLQueryService.java:66)
	at org.hypergraphql.Controller.lambda$start$3(Controller.java:117)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:561)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
```

The schema:

```
type __Context {
    Concept:      _@href(iri: "http://www.w3.org/2004/02/skos/core#Concept")
    Label:        _@href(iri: "http://www.w3.org/2008/05/skos-xl#Label")
    Scheme:       _@href(iri: "http://www.w3.org/2004/02/skos/core#Scheme")
    Collection:   _@href(iri: "http://www.w3.org/2004/02/skos/core#Collection")
    preflabel:    _@href(iri: "http://www.w3.org/2008/05/skos-xl#prefLabel")
    altlabel:     _@href(iri: "http://www.w3.org/2008/05/skos-xl#altLabel")
    literalform:     _@href(iri: "http://www.w3.org/2008/05/skos-xl#literalForm")
    broader:      _@href(iri: "http://www.w3.org/2004/02/skos/core#broader")
    narrower:     _@href(iri: "http://www.w3.org/2004/02/skos/core#narrower")
    inscheme:     _@href(iri: "http://www.w3.org/2004/02/skos/core#inScheme")
    label:        _@href(iri: "http://www.w3.org/2000/01/rdf-schema#")
}

type Concept @service(id:"dkp-sparql") {
    preflabel: [Label!] @service(id:"dkp-sparql")
    altlabel: [Label] @service(id:"dkp-sparql")
    broader: [Concept] @service(id:"dkp-sparql")
    narrower: [Concept] @service(id:"dkp-sparql")
    inscheme: Scheme! @service(id:"dkp-sparql")
}

type Label @service(id:"dkp-sparql") {
    literalform: String! @service(id:"dkp-sparql")
}

type Scheme @service(id:"dkp-sparql") {
    label: String @service(id:"dkp-sparql")
}

type Collection @service(id:"dkp-sparql") {
    label: String @service(id:"dkp-sparql")
}
```

**Comment by pc3356** [comment]
Hello Rinke,

I'm away until Thursday, so I will look at it then.

We're a little under-resourced at the moment or we'd look at it sooner.

Please feel free to raise a bug ticket,

Many thanks,

Philip Coates
Director

SemanticIntegration

+44(0)7711 818384

https://semanticintegration.co.uk

**Comment by pc3356** [comment]
I have a working solution for this in place now, but I am still testing it; as soon as I have done, I'll push the relevant changes.

**Comment by pc3356** [comment]
Please check this against the latest version - v1.0.3
