### ISSUE TITLE
Federating the SPARQL across multiple services

### ISSUE THREAD

**Issue by nkiranrao** [hypergraphql/hypergraphql#24]
I am unable to get the federation working, i have posted my issue in stack-overflow [here ](https://stackoverflow.com/questions/62376420/hypergraphql-federating-the-sparql-across-multiple-services)

can someone help me understand if its possible to construct the shape by linking to entities outside in another SPARQL endpoint. and why do I get the following error:

java.util.concurrent.ExecutionException: HttpException: 400 HTTP 400 error making the query:
 Parse error:  SELECT  * WHERE   { VALUES ?x_2 { <http://localhost:7002/resource/CUSTOMERS/11> }     OPTIONAL       { ?x_2    <http://localhost:7002/resource/vocab/CUSTOMERS_SUPPORTREPID>  ?x_2_1 .         ?x_2_1  a                     <http://localhost:7003/resource/vocab/EMPLOYEES>         OPTIONAL           { ?x_2_1  <http://localhost:7003/resource/vocab/EMPLOYEES_FIRSTNAME>  ?x_2_1_1 }       }   }   
Lexical error at line 3, column 11.  Encountered: " " (32), after : "VALUES"
            at java.util.concurrent.FutureTask.report(Unknown Source)
            at java.util.concurrent.FutureTask.get(Unknown Source)
            at org.hypergraphql.datafetching.services.SPARQLEndpointService.iterateFutureResults(SPARQLEndpointService.java:86)
            at org.hypergraphql.datafetching.services.SPARQLEndpointService.executeQuery(SPARQLEndpointService.java:69)
            at org.hypergraphql.datafetching.ExecutionTreeNode.generateTreeModel(ExecutionTreeNode.java:357)
            at org.hypergraphql.datafetching.FetchingExecution.call(FetchingExecution.java:21)
            at org.hypergraphql.datafetching.FetchingExecution.call(FetchingExecution.java:8)]

**Comment by pc3356** [comment]
It looks like you're writing SQL rather than SPARQL - one isn't a subset of
the other.

Additionally, I can't see what you're actually trying to SELECT from - it
might be worth checking the syntax of the query, as this is probably what's
giving 400s

Many thanks,

*Philip Coates*
*Director*

email: philip.coates@semanticintegration.co.uk
tel: +46 (0)70 2155606
tel: +44 (0)7711 818384

Registered in England and Wales. Company number: 08688966.
*Registered office: 1 Old Court Mews, 311 Chase Road, London, N14 6JS*

**Comment by nkiranrao** [comment]
@pc3356 : Thanks! for responding. Actually its not me generating the SPARQL, its auto generated based on the following GraphQL query:

```
{
  Customers_GET(limit: 1) {
    SupportRep {
      employeeFirstName
    }
  }
}
```
I am now of the opinion that this code is actually working as when I enable DEBUG logging, I am able to see this line in the log 
`[pool-5-thread-1] DEBUG org.apache.jena.riot.web.HttpOp  - [1] GET http://localhost:7003/sparql?query=SELECT  * WHERE  { VALUES ?x_1 { <http://localhost:7002/resource/CUSTOMERS/11> } OPTIONAL { ?x_1 <http://localhost:7002/resource/vocab/CUSTOMERS_SUPPORTREPID> ?x_1_1 . ?x_1_1  a <http://localhost:7003/resource/vocab/EMPLOYEES> OPTIONAL { ?x_1_1  <http://localhost:7003/resource/vocab/EMPLOYEES_FIRSTNAME>  ?x_1_1_1 }}}`

which is basically my SPARQL endpoint at `HR` system, but that system is unable to run this query for whatever reason. DO you have any clue why that might be?
