### ISSUE TITLE
Integration with ApolloClient

### ISSUE THREAD

**Issue by datamusee** [hypergraphql/hypergraphql#44]
Hello
Bravo for that project. I will be very interested for some support of filters.
But for now, I have a problem. I've deployed an hypergraphql server linked to a fuseki rdf dataset.
On  http://localhost:8080/graphiql, the query
```
{
  Takeoff_GET(limit:10) {
    label
    latitude
    longitude
  
     }
}

```give me what I expect.
But using the same query from an ApolloClient, I get the following error in hypergraphql
```
2021-09-12 16:26:01 WARN  SimpleDataFetcherExceptionHandler:26 - Exception while fetching data (/Takeoff_GET) : class graphql.GraphQLContext cannot be cast to class org.hypergraphql.datamodel.ModelContainer (graphql.GraphQLContext and org.hypergraphql.datamodel.ModelContainer are in unnamed module of loader 'app')
java.lang.ClassCastException: class graphql.GraphQLContext cannot be cast to class org.hypergraphql.datamodel.ModelContainer (graphql.GraphQLContext and org.hypergraphql.datamodel.ModelContainer are in unnamed module of loader 'app')
        at org.hypergraphql.datamodel.FetcherFactory.lambda$instancesOfTypeFetcher$2(FetcherFactory.java:44)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:277)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
        at graphql.execution.Execution.executeOperation(Execution.java:167)
        at graphql.execution.Execution.execute(Execution.java:108)
        at graphql.GraphQL.execute(GraphQL.java:598)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:529)
        at graphql.GraphQL.executeAsync(GraphQL.java:493)
        at graphql.GraphQL.execute(GraphQL.java:426)
        at graphql.GraphQL.execute(GraphQL.java:308)
        at org.hypergraphql.services.HGQLQueryService.results(HGQLQueryService.java:58)
        at org.hypergraphql.Controller.lambda$start$3(Controller.java:139)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:501)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:831)

```
Inspecting the request, I can see the payload
```
query: "{\n  Takeoff_GET(limit: 10) {\n    label\n    latitude\n    longitude\n    __typename\n  }\n}\n"
variables: {}
```
ApolloClient seems to add the __typename field, which is not in my submited query. If I try my query with the __typename, I get the same error from graphqli.  For now, I doesn't find how to inhibit ApolloClent from adding __typename or to enable Hypergraphql to manage __typename. 

Any help will be welcome.

**Comment by datamusee** [comment]
The error message visible in graphqli is
 "Exception while fetching data (/Takeoff_GET) : class graphql.GraphQLContext cannot be cast to class org.hypergraphql.datamodel.ModelContainer (graphql.GraphQLContext and org.hypergraphql.datamodel.ModelContainer are in unnamed module of loader 'app')"

**Comment by datamusee** [comment]
See
https://github.com/apollographql/apollo-client/issues/1913
to avoid apolloclient to insert __typename field
(but it could have bad consequences on caching, i'm not sure)
